# -*- coding: utf-8 -*-
"""Website Traffic Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18wkuv5yCc85F8yM1vhWlXw688HrbB7hj
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load and clean data
df = pd.read_csv('/content/traffic.csv')
df.columns = [col.capitalize() for col in df.columns]

# Clean missing values
df_clean = df.copy()
df_clean['Isrc'] = df_clean['Isrc'].fillna('UNKNOWN_ISRC')
df_clean['Album'] = df_clean['Album'].fillna('Unknown Album')
df_clean['Country'] = df_clean['Country'].fillna('Unknown Country')
df_clean['City'] = df_clean['City'].fillna('unknown')
df_clean['Artist'] = df_clean['Artist'].fillna('Unknown Artist')
df_clean['Track'] = df_clean['Track'].fillna('Unknown Track')
df_clean['Date'] = pd.to_datetime(df_clean['Date'])

# VISUALIZATIONS
print(f"\n GENERATING COMPREHENSIVE DASHBOARD...")
fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# 1. Traffic Trend
daily_traffic = df_clean.groupby('Date').size()
axes[0,0].plot(daily_traffic.index, daily_traffic.values, color='#2E86AB', linewidth=2)
axes[0,0].set_title('Daily Traffic Trend', fontweight='bold')
axes[0,0].set_ylabel('Clicks')

# 2. Top Artists
df_clean['Artist'].value_counts().head(8).plot(kind='bar', ax=axes[0,1], color='#A23B72')
axes[0,1].set_title('Top 8 Artists', fontweight='bold')
axes[0,1].tick_params(axis='x', rotation=45)

# 3. Geographic Distribution
df_clean['Country'].value_counts().head(8).plot(kind='bar', ax=axes[0,2], color='#F18F01')
axes[0,2].set_title('Top 8 Countries', fontweight='bold')
axes[0,2].tick_params(axis='x', rotation=45)

# 4. Weekly Pattern
df_clean['DayOfWeek'] = df_clean['Date'].dt.day_name()
weekday_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
daily_pattern = df_clean['DayOfWeek'].value_counts().reindex(weekday_order)
daily_pattern.plot(kind='line', ax=axes[1,0], color='#C73E1D', marker='o')
axes[1,0].set_title('Traffic by Day of Week', fontweight='bold')

# 5. User Engagement Distribution
# Fixed: Defined 'user_engagement' to count occurrences of each ISRC.
user_engagement = df_clean['Isrc'].value_counts() # Count occurrences of each ISRC
user_engagement_counts = user_engagement.value_counts().head(10)
axes[1,1].bar(range(len(user_engagement_counts)), user_engagement_counts.values, color='#3F7CAC')
axes[1,1].set_title('User Engagement Frequency', fontweight='bold')
axes[1,1].set_xlabel('Number of Clicks per User')

# 6. Content Concentration
# Fixed: Defined 'artist_concentration' as the percentage of total events by the top 5 artists.
top_artists_counts = df_clean['Artist'].value_counts()
artist_concentration = (top_artists_counts.head(5).sum() / top_artists_counts.sum()) * 100
sizes = [artist_concentration, 100 - artist_concentration]
axes[1,2].pie(sizes, labels=['Top 5 Artists', 'Others'], autopct='%1.1f%%', colors=['#FF6B6B', '#4ECDC4'])
axes[1,2].set_title('Artist Concentration', fontweight='bold')

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Top Artists
top_artists = df_clean['Artist'].value_counts().head(8)
top_artists.plot(kind='bar', ax=axes[0,0], color='skyblue', title='Top 8 Artists')

# Top Countries
top_countries = df_clean['Country'].value_counts().head(8)
top_countries.plot(kind='bar', ax=axes[0,1], color='lightgreen', title='Top 8 Countries')

# Daily Traffic
daily_traffic = df_clean.groupby('Date').size()
daily_traffic.plot(ax=axes[1,0], color='purple', title='Daily Traffic Trend')

# Event Distribution
df_clean['Event'].value_counts().plot(kind='pie', ax=axes[1,1], autopct='%1.1f%%', title='Event Types')

plt.tight_layout()
plt.show()